# Generated by Django 5.2.3 on 2025-06-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='ישראל', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='קיבולת כללית של האולם. לא חובה אם משתמשים במפת ישיבה.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='כתובת URL לתמונה של האולם', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='SeatingMap',
            fields=[
                ('venue', models.OneToOneField(help_text='האולם אליו שייכת מפת הישיבה (קשר אחד לאחד)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seating_map', serialize=False, to='venues.venue')),
                ('layout_data', models.JSONField(default=dict, help_text='מבנה JSON המתאר את פריסת מפת הישיבה (אזורים, שורות, כיסאות)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seating Map',
                'verbose_name_plural': 'Seating Maps',
            },
        ),
    ]
